<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, sans-serif; font-size: 13px; color: #1a1a1a; padding: 40px; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 12px; margin-bottom: 32px; }
    .section-title { font-size: 13px; font-weight: bold; text-transform: uppercase;
                     letter-spacing: 0.05em; color: #444; border-bottom: 1px solid #ddd;
                     padding-bottom: 4px; margin: 24px 0 12px; }
    table { width: 100%; border-collapse: collapse; }
    table td { padding: 7px 10px; vertical-align: top; }
    table td:first-child { color: #555; width: 40%; }
    .amount-row td { font-size: 16px; font-weight: bold; }
    .status-badge { display: inline-block; padding: 2px 10px; border-radius: 12px;
                    font-size: 11px; font-weight: bold; text-transform: uppercase; }
    .status-unpaid  { background: #fef9c3; color: #854d0e; }
    .status-pending { background: #dbeafe; color: #1e40af; }
    .status-paid    { background: #dcfce7; color: #166534; }
    .footer { margin-top: 48px; font-size: 11px; color: #999; text-align: center; }
    .divider { border: none; border-top: 1px solid #e5e7eb; margin: 0 0 0 0; }
</style>
</head>
<body>

<h1>Invoice</h1>
<p class="subtitle">{{ config('app.name') }} &mdash; {{ now()->format('d F Y') }}</p>

<div class="section-title">Invoice Details</div>
<table>
    <tr>
        <td>Invoice ID</td>
        <td>#{{ strtoupper(substr($invoice->id, 0, 8)) }}</td>
    </tr>
    <tr class="amount-row">
        <td>Amount</td>
        <td>Rp {{ number_format($invoice->amount, 0, ',', '.') }}</td>
    </tr>
    <tr>
        <td>Status</td>
        <td>
            <span class="status-badge status-{{ $invoice->status->value }}">
                {{ $invoice->status->value }}
            </span>
        </td>
    </tr>
    @if($invoice->paid_at)
    <tr>
        <td>Paid Date</td>
        <td>{{ $invoice->paid_at->format('d F Y') }}</td>
    </tr>
    @endif
</table>

<div class="section-title">Campaign</div>
<table>
    <tr>
        <td>Campaign</td>
        <td>{{ $campaign->name }}</td>
    </tr>
    @if($campaign->start_date)
    <tr>
        <td>Start Date</td>
        <td>{{ $campaign->start_date->format('d F Y') }}</td>
    </tr>
    @endif
    @if($campaign->end_date)
    <tr>
        <td>End Date</td>
        <td>{{ $campaign->end_date->format('d F Y') }}</td>
    </tr>
    @endif
</table>

<div class="section-title">Influencer / KOL</div>
<table>
    <tr>
        <td>Influencer</td>
        <td>{{ $invoice->influencer?->name ?? '—' }}</td>
    </tr>
    @if($invoice->keyOpinionLeader)
    <tr>
        <td>Platform</td>
        <td>{{ $invoice->keyOpinionLeader->platform_name }}</td>
    </tr>
    <tr>
        <td>Username</td>
        <td>{{ $invoice->keyOpinionLeader->username }}</td>
    </tr>
    @endif
    @if($pivot?->deliverable)
    <tr>
        <td>Deliverable</td>
        <td>{{ $pivot->deliverable }}</td>
    </tr>
    @endif
</table>

@if($invoice->notes)
<div class="section-title">Notes</div>
<p style="padding: 8px 10px; background: #f9fafb; border-radius: 4px;">{{ $invoice->notes }}</p>
@endif

<div class="footer">
    Generated by {{ config('app.name') }} on {{ now()->format('d F Y H:i') }}
</div>

</body>
</html>
